name: Run Shantanu Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */90 * * *'  # Corrected cron format

jobs:
  run_shantanu_workflow:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Make script executable
        run: chmod +x shan

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install required packages
        run: pip install python-telegram-bot

      - name: Run public.py
        run: python3 public.py
        
